export const countriesList = [
  { label: 'Andorra', code: 'AD', phone: '376' },
  { label: 'United Arab Emirates', code: 'AE', phone: '971' },
  { label: 'Afghanistan', code: 'AF', phone: '93' },
  { label: 'Antigua and Barbuda', code: 'AG', phone: '1-268' },
  { label: 'Anguilla', code: 'AI', phone: '1-264' },
  { label: 'Albania', code: 'AL', phone: '355' },
  { label: 'Armenia', code: 'AM', phone: '374' },
  { label: 'Angola', code: 'AO', phone: '244' },
  { label: 'Antarctica', code: 'AQ', phone: '672' },
  { label: 'Argentina', code: 'AR', phone: '54' },
  { label: 'American Samoa', code: 'AS', phone: '1-684' },
  { label: 'Austria', code: 'AT', phone: '43' },
  { label: 'Australia', code: 'AU', phone: '61' },
  { label: 'Aruba', code: 'AW', phone: '297' },
  { label: 'Alland Islands', code: 'AX', phone: '358' },
  { label: 'Azerbaijan', code: 'AZ', phone: '994' },
  { label: 'Bosnia and Herzegovina', code: 'BA', phone: '387' },
  { label: 'Barbados', code: 'BB', phone: '1-246' },
  { label: 'Bangladesh', code: 'BD', phone: '880' },
  { label: 'Belgium', code: 'BE', phone: '32' },
  { label: 'Burkina Faso', code: 'BF', phone: '226' },
  { label: 'Bulgaria', code: 'BG', phone: '359' },
  { label: 'Bahrain', code: 'BH', phone: '973' },
  { label: 'Burundi', code: 'BI', phone: '257' },
  { label: 'Benin', code: 'BJ', phone: '229' },
  { label: 'Saint Barthelemy', code: 'BL', phone: '590' },
  { label: 'Bermuda', code: 'BM', phone: '1-441' },
  { label: 'Brunei Darussalam', code: 'BN', phone: '673' },
  { label: 'Bolivia', code: 'BO', phone: '591' },
  { label: 'Brazil', code: 'BR', phone: '55' },
  { label: 'Bahamas', code: 'BS', phone: '1-242' },
  { label: 'Bhutan', code: 'BT', phone: '975' },
  { label: 'Bouvet Island', code: 'BV', phone: '47' },
  { label: 'Botswana', code: 'BW', phone: '267' },
  { label: 'Belarus', code: 'BY', phone: '375' },
  { label: 'Belize', code: 'BZ', phone: '501' },
  { label: 'Canada', code: 'CA', phone: '1' },
  { label: 'Cocos (Keeling) Islands', code: 'CC', phone: '61' },
  { label: 'Congo, Democratic Republic of the', code: 'CD', phone: '243' },
  { label: 'Central African Republic', code: 'CF', phone: '236' },
  { label: 'Congo, Republic of the', code: 'CG', phone: '242' },
  { label: 'Switzerland', code: 'CH', phone: '41' },
  { label: "Cote d'Ivoire", code: 'CI', phone: '225' },
  { label: 'Cook Islands', code: 'CK', phone: '682' },
  { label: 'Chile', code: 'CL', phone: '56' },
  { label: 'Cameroon', code: 'CM', phone: '237' },
  { label: 'China', code: 'CN', phone: '86' },
  { label: 'Colombia', code: 'CO', phone: '57' },
  { label: 'Costa Rica', code: 'CR', phone: '506' },
  { label: 'Cuba', code: 'CU', phone: '53' },
  { label: 'Cape Verde', code: 'CV', phone: '238' },
  { label: 'Curacao', code: 'CW', phone: '599' },
  { label: 'Christmas Island', code: 'CX', phone: '61' },
  { label: 'Cyprus', code: 'CY', phone: '357' },
  { label: 'Czech Republic', code: 'CZ', phone: '420' },
  { label: 'Germany', code: 'DE', phone: '49' },
  { label: 'Djibouti', code: 'DJ', phone: '253' },
  { label: 'Denmark', code: 'DK', phone: '45' },
  { label: 'Dominica', code: 'DM', phone: '1-767' },
  { label: 'Dominican Republic', code: 'DO', phone: '1-809' },
  { label: 'Algeria', code: 'DZ', phone: '213' },
  { label: 'Ecuador', code: 'EC', phone: '593' },
  { label: 'Estonia', code: 'EE', phone: '372' },
  { label: 'Egypt', code: 'EG', phone: '20' },
  { label: 'Western Sahara', code: 'EH', phone: '212' },
  { label: 'Eritrea', code: 'ER', phone: '291' },
  { label: 'Spain', code: 'ES', phone: '34' },
  { label: 'Ethiopia', code: 'ET', phone: '251' },
  { label: 'Finland', code: 'FI', phone: '358' },
  { label: 'Fiji', code: 'FJ', phone: '679' },
  { label: 'Falkland Islands (Malvinas)', code: 'FK', phone: '500' },
  { label: 'Micronesia, Federated States of', code: 'FM', phone: '691' },
  { label: 'Faroe Islands', code: 'FO', phone: '298' },
  { label: 'France', code: 'FR', phone: '33' },
  { label: 'Gabon', code: 'GA', phone: '241' },
  { label: 'United Kingdom', code: 'GB', phone: '44' },
  { label: 'Grenada', code: 'GD', phone: '1-473' },
  { label: 'Georgia', code: 'GE', phone: '995' },
  { label: 'French Guiana', code: 'GF', phone: '594' },
  { label: 'Guernsey', code: 'GG', phone: '44' },
  { label: 'Ghana', code: 'GH', phone: '233' },
  { label: 'Gibraltar', code: 'GI', phone: '350' },
  { label: 'Greenland', code: 'GL', phone: '299' },
  { label: 'Gambia', code: 'GM', phone: '220' },
  { label: 'Guinea', code: 'GN', phone: '224' },
  { label: 'Guadeloupe', code: 'GP', phone: '590' },
  { label: 'Equatorial Guinea', code: 'GQ', phone: '240' },
  { label: 'Greece', code: 'GR', phone: '30' },
  { label: 'South Georgia and the South Sandwich Islands', code: 'GS', phone: '500' },
  { label: 'Guatemala', code: 'GT', phone: '502' },
  { label: 'Guam', code: 'GU', phone: '1-671' },
  { label: 'Guinea-Bissau', code: 'GW', phone: '245' },
  { label: 'Guyana', code: 'GY', phone: '592' },
  { label: 'Hong Kong', code: 'HK', phone: '852' },
  { label: 'Heard Island and McDonald Islands', code: 'HM', phone: '672' },
  { label: 'Honduras', code: 'HN', phone: '504' },
  { label: 'Croatia', code: 'HR', phone: '385' },
  { label: 'Haiti', code: 'HT', phone: '509' },
  { label: 'Hungary', code: 'HU', phone: '36' },
  { label: 'Indonesia', code: 'ID', phone: '62' },
  { label: 'Ireland', code: 'IE', phone: '353' },
  { label: 'Israel', code: 'IL', phone: '972' },
  { label: 'Isle of Man', code: 'IM', phone: '44' },
  { label: 'India', code: 'IN', phone: '91' },
  { label: 'British Indian Ocean Territory', code: 'IO', phone: '246' },
  { label: 'Iraq', code: 'IQ', phone: '964' },
  { label: 'Iran, Islamic Republic of', code: 'IR', phone: '98' },
  { label: 'Iceland', code: 'IS', phone: '354' },
  { label: 'Italy', code: 'IT', phone: '39' },
  { label: 'Jersey', code: 'JE', phone: '44' },
  { label: 'Jamaica', code: 'JM', phone: '1-876' },
  { label: 'Jordan', code: 'JO', phone: '962' },
  { label: 'Japan', code: 'JP', phone: '81' },
  { label: 'Kenya', code: 'KE', phone: '254' },
  { label: 'Kyrgyzstan', code: 'KG', phone: '996' },
  { label: 'Cambodia', code: 'KH', phone: '855' },
  { label: 'Kiribati', code: 'KI', phone: '686' },
  { label: 'Comoros', code: 'KM', phone: '269' },
  { label: 'Saint Kitts and Nevis', code: 'KN', phone: '1-869' },
  { label: "Korea, Democratic People's Republic of", code: 'KP', phone: '850' },
  { label: 'Korea, Republic of', code: 'KR', phone: '82' },
  { label: 'Kuwait', code: 'KW', phone: '965' },
  { label: 'Cayman Islands', code: 'KY', phone: '1-345' },
  { label: 'Kazakhstan', code: 'KZ', phone: '7' },
  { label: "Lao People's Democratic Republic", code: 'LA', phone: '856' },
  { label: 'Lebanon', code: 'LB', phone: '961' },
  { label: 'Saint Lucia', code: 'LC', phone: '1-758' },
  { label: 'Liechtenstein', code: 'LI', phone: '423' },
  { label: 'Sri Lanka', code: 'LK', phone: '94' },
  { label: 'Liberia', code: 'LR', phone: '231' },
  { label: 'Lesotho', code: 'LS', phone: '266' },
  { label: 'Lithuania', code: 'LT', phone: '370' },
  { label: 'Luxembourg', code: 'LU', phone: '352' },
  { label: 'Latvia', code: 'LV', phone: '371' },
  { label: 'Libya', code: 'LY', phone: '218' },
  { label: 'Morocco', code: 'MA', phone: '212' },
  { label: 'Monaco', code: 'MC', phone: '377' },
  { label: 'Moldova, Republic of', code: 'MD', phone: '373' },
  { label: 'Montenegro', code: 'ME', phone: '382' },
  { label: 'Saint Martin (French part)', code: 'MF', phone: '590' },
  { label: 'Madagascar', code: 'MG', phone: '261' },
  { label: 'Marshall Islands', code: 'MH', phone: '692' },
  { label: 'Macedonia, the Former Yugoslav Republic of', code: 'MK', phone: '389' },
  { label: 'Mali', code: 'ML', phone: '223' },
  { label: 'Myanmar', code: 'MM', phone: '95' },
  { label: 'Mongolia', code: 'MN', phone: '976' },
  { label: 'Macao', code: 'MO', phone: '853' },
  { label: 'Northern Mariana Islands', code: 'MP', phone: '1-670' },
  { label: 'Martinique', code: 'MQ', phone: '596' },
  { label: 'Mauritania', code: 'MR', phone: '222' },
  { label: 'Montserrat', code: 'MS', phone: '1-664' },
  { label: 'Malta', code: 'MT', phone: '356' },
  { label: 'Mauritius', code: 'MU', phone: '230' },
  { label: 'Maldives', code: 'MV', phone: '960' },
  { label: 'Malawi', code: 'MW', phone: '265' },
  { label: 'Mexico', code: 'MX', phone: '52' },
  { label: 'Malaysia', code: 'MY', phone: '60' },
  { label: 'Mozambique', code: 'MZ', phone: '258' },
  { label: 'Namibia', code: 'NA', phone: '264' },
  { label: 'New Caledonia', code: 'NC', phone: '687' },
  { label: 'Niger', code: 'NE', phone: '227' },
  { label: 'Norfolk Island', code: 'NF', phone: '672' },
  { label: 'Nigeria', code: 'NG', phone: '234' },
  { label: 'Nicaragua', code: 'NI', phone: '505' },
  { label: 'Netherlands', code: 'NL', phone: '31' },
  { label: 'Norway', code: 'NO', phone: '47' },
  { label: 'Nepal', code: 'NP', phone: '977' },
  { label: 'Nauru', code: 'NR', phone: '674' },
  { label: 'Niue', code: 'NU', phone: '683' },
  { label: 'New Zealand', code: 'NZ', phone: '64' },
  { label: 'Oman', code: 'OM', phone: '968' },
  { label: 'Panama', code: 'PA', phone: '507' },
  { label: 'Peru', code: 'PE', phone: '51' },
  { label: 'French Polynesia', code: 'PF', phone: '689' },
  { label: 'Papua New Guinea', code: 'PG', phone: '675' },
  { label: 'Philippines', code: 'PH', phone: '63' },
  { label: 'Pakistan', code: 'PK', phone: '92' },
  { label: 'Poland', code: 'PL', phone: '48' },
  { label: 'Saint Pierre and Miquelon', code: 'PM', phone: '508' },
  { label: 'Pitcairn', code: 'PN', phone: '870' },
  { label: 'Puerto Rico', code: 'PR', phone: '1' },
  { label: 'Palestine, State of', code: 'PS', phone: '970' },
  { label: 'Portugal', code: 'PT', phone: '351' },
  { label: 'Palau', code: 'PW', phone: '680' },
  { label: 'Paraguay', code: 'PY', phone: '595' },
  { label: 'Qatar', code: 'QA', phone: '974' },
  { label: 'Reunion', code: 'RE', phone: '262' },
  { label: 'Romania', code: 'RO', phone: '40' },
  { label: 'Serbia', code: 'RS', phone: '381' },
  { label: 'Russian Federation', code: 'RU', phone: '7' },
  { label: 'Rwanda', code: 'RW', phone: '250' },
  { label: 'Saudi Arabia', code: 'SA', phone: '966' },
  { label: 'Solomon Islands', code: 'SB', phone: '677' },
  { label: 'Seychelles', code: 'SC', phone: '248' },
  { label: 'Sudan', code: 'SD', phone: '249' },
  { label: 'Sweden', code: 'SE', phone: '46' },
  { label: 'Singapore', code: 'SG', phone: '65' },
  { label: 'Saint Helena', code: 'SH', phone: '290' },
  { label: 'Slovenia', code: 'SI', phone: '386' },
  { label: 'Svalbard and Jan Mayen', code: 'SJ', phone: '47' },
  { label: 'Slovakia', code: 'SK', phone: '421' },
  { label: 'Sierra Leone', code: 'SL', phone: '232' },
  { label: 'San Marino', code: 'SM', phone: '378' },
  { label: 'Senegal', code: 'SN', phone: '221' },
  { label: 'Somalia', code: 'SO', phone: '252' },
  { label: 'Surilabel', code: 'SR', phone: '597' },
  { label: 'South Sudan', code: 'SS', phone: '211' },
  { label: 'Sao Tome and Principe', code: 'ST', phone: '239' },
  { label: 'El Salvador', code: 'SV', phone: '503' },
  { label: 'Sint Maarten (Dutch part)', code: 'SX', phone: '1-721' },
  { label: 'Syrian Arab Republic', code: 'SY', phone: '963' },
  { label: 'Swaziland', code: 'SZ', phone: '268' },
  { label: 'Turks and Caicos Islands', code: 'TC', phone: '1-649' },
  { label: 'Chad', code: 'TD', phone: '235' },
  { label: 'French Southern Territories', code: 'TF', phone: '262' },
  { label: 'Togo', code: 'TG', phone: '228' },
  { label: 'Thailand', code: 'TH', phone: '66' },
  { label: 'Tajikistan', code: 'TJ', phone: '992' },
  { label: 'Tokelau', code: 'TK', phone: '690' },
  { label: 'Timor-Leste', code: 'TL', phone: '670' },
  { label: 'Turkmenistan', code: 'TM', phone: '993' },
  { label: 'Tunisia', code: 'TN', phone: '216' },
  { label: 'Tonga', code: 'TO', phone: '676' },
  { label: 'Turkey', code: 'TR', phone: '90' },
  { label: 'Trinidad and Tobago', code: 'TT', phone: '1-868' },
  { label: 'Tuvalu', code: 'TV', phone: '688' },
  { label: 'Taiwan, Province of China', code: 'TW', phone: '886' },
  { label: 'United Republic of Tanzania', code: 'TZ', phone: '255' },
  { label: 'Ukraine', code: 'UA', phone: '380' },
  { label: 'Uganda', code: 'UG', phone: '256' },
  { label: 'United States', code: 'US', phone: '1' },
  { label: 'Uruguay', code: 'UY', phone: '598' },
  { label: 'Uzbekistan', code: 'UZ', phone: '998' },
  { label: 'Holy See (Vatican City State)', code: 'VA', phone: '379' },
  { label: 'Saint Vincent and the Grenadines', code: 'VC', phone: '1-784' },
  { label: 'Venezuela', code: 'VE', phone: '58' },
  { label: 'British Virgin Islands', code: 'VG', phone: '1-284' },
  { label: 'US Virgin Islands', code: 'VI', phone: '1-340' },
  { label: 'Vietnam', code: 'VN', phone: '84' },
  { label: 'Vanuatu', code: 'VU', phone: '678' },
  { label: 'Wallis and Futuna', code: 'WF', phone: '681' },
  { label: 'Samoa', code: 'WS', phone: '685' },
  { label: 'Kosovo', code: 'XK', phone: '383' },
  { label: 'Yemen', code: 'YE', phone: '967' },
  { label: 'Mayotte', code: 'YT', phone: '262' },
  { label: 'South Africa', code: 'ZA', phone: '27' },
  { label: 'Zambia', code: 'ZM', phone: '260' },
  { label: 'Zimbabwe', code: 'ZW', phone: '263' },
]
